#!/usr/bin/python3

def input_validation():
    try:
        value = int(input(">> "))
        return value

    except ValueError:
        return "ValueError"
        
    except KeyboardInterrupt:
        return "KeyboardInterrupt"



def how_many_passwords():
    print("How many passwords do you want to generate?")
    the_integer = input_validation()

    if the_integer == "KeyboardInterrupt":
        print("Keyboard Interrupt!")

        return "KeyboardInterrupt"
    
    elif the_integer == "ValueError":
        print("Error: Value Error")

        return "ValueError"
    
    else:
        return the_integer



def how_long_passwords():
    print("How long should the generated passwords be?")
    the_integer = input_validation()

    if the_integer == "KeyboardInterrupt":
        print("Keyboard Interrupt!")

        return "KeyboardInterrupt"
    
    elif the_integer == "ValueError":
        print("Error: Value Error")

        return "ValueError"
    
    else:
        return the_integer



def password_generation():
    import random
    
    try:
        the_characters_for_password = []
        type_of_symbol = "luio"
        how_many = 0
        the_length = 0
        generate = True
        
        for i in range(2):
            if i == 0:
                how_much = how_many_passwords()

                if how_much != "ValueError" and how_much != "KeyboardInterrupt":
                    how_many += how_much
                else:
                    generate = False
                    break 
            else:
                how_many = how_long_passwords()

                if how_many != "ValueError" and how_much != "KeyboardInterrupt":
                    the_length += how_many 
                else:
                    generate = False
                    break
                    
        if generate == True:
            if how_many_passwords == 1:
                print("Generated Password:-")
            else:
                print("Generated Passwords:-")
                for p in range(how_many):
                    for l in range(the_length):
                        password_character_choosing = random.choice(type_of_symbol)
                        
                        if password_character_choosing == "l":
                            the_characters_for_password.append(random.choice("qwertyuiopasdfghjklzxcvbnm"))
                        elif password_character_choosing == "u":
                            the_characters_for_password.append(random.choice("QWERTYUIOPASDFGHJKLZXCVBNM"))
                        elif password_character_choosing== "i":
                            the_characters_for_password.append(random.choice("1234567890"))
                        else:
                            the_characters_for_password.append(random.choice("!£$%^&*()_-=[]{.};:<>,.|'@'?~#+/"))
                    
                    print(f"The password: {''.join(the_characters_for_password)}")
                    the_characters_for_password.clear()
    
    except KeyboardInterrupt:
        print("Keyboard Interrupt!")



def main():
    password_generation()



main()

