#!/usr/bin/python3

def user_input():
    try:
        how_many = 0
        the_length = 0

        for i in range(2):
            if i == 0:
                print("Enter how many passwords you want to generate.")

                the_amount_to_generate = int(input(">> "))
                how_many += the_amount_to_generate
            else:
                print("Enter how long the passwords should be.")

                the_length_to_generate = int(input(">> "))
                the_length += the_length_to_generate
        
        password_generation(how_many, the_length)
        
    except KeyboardInterrupt:
        print("Keyboard Interrupt!")
    except ValueError:
        print("Error: Value Error!")



def password_generation(how_many, the_length):
    import secrets

    the_characters_for_password = []
    run_password_generation = True
    how_many = how_many
    the_length = the_length

    match how_many:
        case 0:
            run_password_generation = False
        case 1:
            print("Generated Password:-")
        case _:
            print("Generated Passwords:-")
    
    for p in range(how_many):
        for l in range(the_length):
            the_characters_for_password.append(secrets.choice("qwertyuiopasdfghjklzxcvbnmQWERTYUIOPASDFGHJKLZXCVBNM1234567890!£$%^&*()_-=[]{.};:<>,.|'@'?~#+/"))
                    
        print(f"The password: {''.join(the_characters_for_password)}")
        the_characters_for_password.clear()
    



def main():
    user_input()



if __name__ == "__main__":
    main()
